CREATE TABLE IF NOT EXISTS guests (
  id SERIAL PRIMARY KEY,
  full_name VARCHAR(250) NOT NULL,
  additionals INTEGER NOT NULL DEFAULT 0,
  confirm_attendance BOOLEAN NOT NULL DEFAULT FALSE,
  table_id INTEGER REFERENCES tables(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
