CREATE TABLE IF NOT EXISTS generals (
  id SERIAL PRIMARY KEY,
  folio VARCHAR(250) NOT NULL,
  table_id INTEGER REFERENCES tables(id) ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  qr_code_url VARCHAR(250),
  pdf_file VARCHAR(250)
);
